services:
  relay:
    build:
      context: ../..
      dockerfile: crates/server/Dockerfile
    image: nt_server
    ports:
      - "8080:8080/udp"
    env_file:
      - .env
    restart: unless-stopped
